spring.application.name=catalogservice

server.port=8081

#H2
spring.datasource.url=jdbc:h2:file:./data/catalog-service
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#RAWG
rawg.api.base-url=https://api.rawg.io/api
rawg.api.key=${RAWG_API_KEY}

#EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=2
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.default-requeue-rejected=false

#ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

#TRACING
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.enabled=false
spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true

#LOGS
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:3100/otlp/v1/logs
